### ISSUE TITLE
docs: add license

### ISSUE THREAD

**Issue by AngryMaciek** [pgrobecker/cellstates#2]
The repository does not have any (open source) license yet, which means that **technically no one can use/modify this work** (take a look [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)).  It would be very beneficial to add one. This link might be helpful: https://choosealicense.com/

I usually use _Apache ver 2.0_ or _MIT_.

**Comment by pgrobecker** [comment]
Thanks a lot for all of your feedback! I've started by adding the an MIT license, so anyone can make changes now.
