### ISSUE TITLE
docs: refactor README

### ISSUE THREAD

**Issue by AngryMaciek** [pgrobecker/cellstates#6]
I would suggest minor modifications to the README.md file:
* keep headling level 1 reserved only for the project title, every other section should start from H2, it would be a little more clear to read.
* >Installation of the cellstate python package can simply be done by going in the package folder and running

end of the sentence is missing?
* >Python packages Mandatory: numpy, pandas, matplotlib, scipy

I would introduce bullet points for mandatory/recomennded.
* the use of **bold** throughout the instructions is not very consistent...

**Comment by pgrobecker** [comment]
Thanks, I've updated it
